### ISSUE TITLE
No logs when using zbctl via npm compared to the zbctl binary

### ISSUE THREAD

**Issue by Sijoma** [jwulf/zbctl#8]
When using the following command I have different behaviour with the NPM packaged version. Both are version 0.26.

`zbctl create worker test-worker --handler "echo {\"return\":\"Pong\"}"` 

NPM version
No console output

With Binary version from https://github.com/camunda-cloud/zeebe/releases:
```
2021/05/06 13:02:25 Activated job 2251799813685559 with variables {}
2021/05/06 13:02:25 Handler completed job 2251799813685559 with variables {"return":"Ping"}
```

**Comment by jwulf** [comment]
Thanks for reporting this @Sijoma 

I published 1.0.1, which is a breaking change and is compatible with 1.0 brokers and later.

It uses `spawn` instead of `spawnSync`.  Hopefully this will pass the std from the handler all the way back to the console.

Are you able to try this release with a 1.0 broker?

**Comment by Sijoma** [comment]
Will do soon!

**Comment by Sijoma** [comment]
It works. I now receive: 

2021/05/28 13:45:45 Activated job 4503599627370507 with variables {}

2021/05/28 13:45:45 Handler completed job 4503599627370507 with variables {"return":"Pong"}
